film_categorie:
    path:     /categorie
    defaults: { _controller: FilmBundle:Default:categorieFilm }
    
film_gestionBa:
    path:     /gestionBa
    defaults: { _controller: FilmBundle:Default:gestionBa }
    
film_liste:
    path:     /liste
    defaults: { _controller: FilmBundle:Default:gestionFilms }
    
film_homepage:
    path:     /{id}
    defaults: { _controller: FilmBundle:Default:ficheFilm }