film_categorie:
    path:     /categorie
    defaults: { _controller: FilmBundle:Default:categorieFilm }
    
film_gestionBa:
    path:     /gestionBa
    defaults: { _controller: FilmBundle:Default:gestionDifBa }
    
film_liste:
    path:     /gererFilms
    defaults: { _controller: FilmBundle:Default:gestionFilms }

film_liste_ajout:
    path:     /ajoutFilm
    defaults: { _controller: FilmBundle:Default:ajoutFilm }

film_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: FilmBundle:Default:supprimeFilm }
    
film_homepage:
    path:     /{id}
    defaults: { _controller: FilmBundle:Default:ficheFilm }