bibliSymfony_base_login:
    path:     /login
    defaults: { _controller: BaseBundle:Default:login }
    
bibliSymfony_base_users:
    path:     /users
    defaults: { _controller: BaseBundle:Default:gestionUtilisateurs }

bibliSymfony_base_location:
    path:     /{id}
    defaults: { _controller: BaseBundle:Default:gestionLocations }

bibliSymfony_base_accueil:
    path:     /
    defaults: { _controller: BaseBundle:Default:bienvenue }