<?php

namespace Proxies\__CG__\BibliSymfony\FilmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Film extends \BibliSymfony\FilmBundle\Entity\Film implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'id', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'titre', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'description', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'lienFilm', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'lienBa', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'tarif', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'nouveaute', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'baDif');
        }

        return array('__isInitialized__', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'id', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'titre', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'description', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'lienFilm', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'lienBa', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'tarif', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'nouveaute', '' . "\0" . 'BibliSymfony\\FilmBundle\\Entity\\Film' . "\0" . 'baDif');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Film $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienFilm($lienFilm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienFilm', array($lienFilm));

        return parent::setLienFilm($lienFilm);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienFilm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienFilm', array());

        return parent::getLienFilm();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienBa($lienBa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienBa', array($lienBa));

        return parent::setLienBa($lienBa);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienBa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienBa', array());

        return parent::getLienBa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarif($tarif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarif', array($tarif));

        return parent::setTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', array());

        return parent::getTarif();
    }

    /**
     * {@inheritDoc}
     */
    public function setNouveaute($nouveaute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNouveaute', array($nouveaute));

        return parent::setNouveaute($nouveaute);
    }

    /**
     * {@inheritDoc}
     */
    public function getNouveaute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNouveaute', array());

        return parent::getNouveaute();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaDif($baDif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaDif', array($baDif));

        return parent::setBaDif($baDif);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaDif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaDif', array());

        return parent::getBaDif();
    }

}
